AWSTemplateFormatVersion: 2010-09-09

Resources:
  SubnetMGMT:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: <%=vpc%>
      AvailabilityZone: <%=mgmt_subnet_zone%>
      CidrBlock:  <%=mgmt_subnet_cidr%>
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Environment
          Value: <%=env_name%>
        - Key: Name
          Value: mgmt-subnet-<%=env_name%>
  
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open web access and ssh for maintenance
      VpcId: <%=vpc%>
      Tags:
        - Key: Environment
          Value: <%=env_name%>

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: <%=mgmt_instance_type%>
      ImageId: <%=mgmt_instance_ami%>
      KeyName: <%=mgmt_instance_keypair_name%>
      NetworkInterfaces:
        - DeviceIndex: '0'
          DeleteOnTermination: 'true'
          AssociatePublicIpAddress: 'true'
          SubnetId: !Ref SubnetMGMT
          GroupSet: 
             - Ref: EC2SecurityGroup
      Tags:
        - Key: Environment
          Value: <%=env_name%>
        - Key: Name
          Value: mgmt-<%=env_name%>

Outputs:
  PrivateIp:
    Description: <%=env_name%> mgmt instance private IP
    Value: !GetAtt EC2Instance.PrivateIp
  PublicIp:
    Description: <%=env_name%> mgmt instance public IP
    Value: !GetAtt EC2Instance.PublicIp
  MgmtSecurityGroupId:
    Description: <%=env_name%> mgmt security group identifier
    Value: !GetAtt [EC2SecurityGroup, GroupId]
  InstanceId:
    Description: <%=env_name%> mgmt instance identifier
    Value: !Ref "EC2Instance"
